apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-flask
spec:
  selector:
    matchLabels:
      app: ml-flask
  template:
    metadata:
      labels:
        app: ml-flask
    spec:
      containers:
      - name: ml-flask
        image: tamermohamed/ml-microservice-kubernetes:version1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
